info: |
    Parallel coordinates plot that allows brushing, and moving the axes.

    Parameters
    "color_by" is the name of the column that is used to generate the color palette.
    If not specified explicitly, the template uses the first numeric column.

    "domain" will be used to set the domain of the color palette.
    Because it uses the D3 domain function, it can be a vector of 2 elements c(min, max)
    or 3 c(min, middle, max).

    "from_color" is the starting color of the palette. It can be specified by a name ("red") or hex ("#FFFF33")

    "to_color" is the ending color of the palette. It can be specified by a name ("red") or hex ("#FFFF33")


valid_names:

name_comments: |


scripts:
    - d3.min.js
    - d3.parcoords.js

styles:
    - d3.parcoords.css
    - style.css

default_parameters: {
    color_by,
    domain,
    from_color: "steelblue",
    to_color: "brown",
    width: 960,
    height: 200,
}

require_packages:

require_server: yes

original_url: http://syntagmatic.github.com/parallel-coordinates/examples/brushing.html

demo: |
    cars <- read_ractive_csv("par_coords", "original_data.csv")
    clickme(cars, "par_coords")


