info: |-
    A zoomable scatterplot

    Based on ideas from:
    http://bl.ocks.org/mbostock/3680957
    http://bl.ocks.org/stepheneb/1182434
    http://www.nytimes.com/interactive/2013/05/25/sunday-review/corporate-taxes.html

original_url:

demo: |-
    clickme(points, rnorm(100))

    clickme(points, x = c(rbeta(100, 1, 10), y = rbeta(100, 1, 10)),
            names = sample(letters, 100, r = T),
            color_groups = sample(LETTERS[1:3], 100, r = T),
            title = "Zoom Search Hover Click")

    data(microarray)
    clickme(points, x = microarray$significance, y = microarray$logFC,
            color_groups = ifelse(microarray$adj.P.Val < 1e-4, "Significant", "Noise"),
            names = microarray$gene_name,
            xlab = "Significance (-log10)", ylab = "Fold-change (log2)",
            extra = list(Probe = microarray$probe_name))



scripts:
    - $shared/d3.v3.2.7.js
    - $shared/jquery.v1.8.3.min.js
    - $shared/bootstrap-tooltip.v2.3.0.js
    - $shared/d3_aux.js

styles:
    - $shared/clickme.css
    - $shared/tooltip.css
    - points.css

require_packages:

require_server: no
