info: |
    Show a graph with directed connections. The nodes are movable.

valid_names:
    - source
    - target
    - type

name_comments: |
    "source" is the beginning of the arrow
    "target" is the end of the arrow
    "type" is the type of arrow (color)

scripts:
    - d3.min.js

styles:
    - main.css

default_parameters: {
    width: 800,
    height: 800,
}

require_packages:
    - df2json

require_server: no

original_url: http://bl.ocks.org/mbostock/1153292

demo: |
    items <- paste0("GENE_", 1:40)
    n <- 30
    data <- data.frame(a = sample(items, n, replace = TRUE), b = sample(items, n, replace = TRUE), type = sample(letters[1:3], n, replace=TRUE))
    clickme(data, "force_directed")
